name: Nightly

on:
  schedule:
    - cron: "0 5/17 * * *"

env: 
  CARGO_TERM_COLOR: always

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-ci-${{ hashFiles('**/Cargo.toml') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add wasm32-unknown-unknown
      - run: cp .env.default .env
      - run: cargo build --verbose
      - run: cargo bench --workspace --verbose
      - run: cargo bench --bench simple -- --profile-time=5
        working-directory: libs/tests
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/criterion
          destination_dir: build/criterion

